### ISSUE TITLE
Unpack Sound/Terrain Textures?

### ISSUE THREAD

**Issue by nyfrk** [WizzardMaker/S4GFX#3]
Hi WizzardMaker,

Thank you for this awesome tool and thank you very much for making it public!

* Would it be possible to also unpack the sound files (not the background music, but the sounds like the hammering when erecting a building) ?

* Also, can you implement the unpacking of the terrain textures? I think they are stored in the .gh files probably with different mip levels (?). It seems your unpacker does not yet support these.

I am really bad at reverse engineering the file formats and hope you can help or at least have an idea on how to unpack them.

**Comment by WizzardMaker** [comment]
The terrain textures are planned and already reverse engineered.
Expect the feature next week

**Comment by WizzardMaker** [comment]
Terrain support added with 099ae2d4a77ca9ae8a3f245b74aa0c38affe549b
