### ISSUE TITLE
[FEATURE] Adding a readme file

### ISSUE THREAD

**Issue by XanatosX** [WizzardMaker/S4GFX#6]
## What is requested

#5 mentioned in the comment from nyfrk we should add a short readme file on how to create a working build and how to use the tool.

**Comment by WizzardMaker** [comment]
Needs to have the following in no particular order:
- Current state of the project (what is working, what not yet)
- Build steps
- Usage tutorial
- limitations like #4 
- hint at the (near future) wiki with all the file specifications

**Comment by XanatosX** [comment]
I did think a little bit more about this.

**Comment by WizzardMaker** [comment]
Readme added with 2f0a04843d5e41c8904c0b6b0db16dcb3634cbc6
